services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ucr
      POSTGRES_PASSWORD: ucr_password
      POSTGRES_DB: ucr_erp
    ports:
      - "5432:5432"
    volumes:
      - ucr_pgdata:/var/lib/postgresql/data

volumes:
  ucr_pgdata:
